name: crispri
channels:
  - conda-forge
  - pyviz
  - bioconda
  - pytorch
  - r
dependencies:
  - anndata2ri
  - arch-py
  - bioconductor-s4vectors
  - bioconductor-singlecellexperiment
  - biopython
  - black
  - bokeh
  - cudatoolkit=10.2
  - dask
  - dask-jobqueue
  - dask-ml
  - datashader
  - distributed
  - dna_features_viewer
  - fastparquet
  - goatools
  - h5py
  - holoviews
  - imgaug
  - ipympl
  - ipywidgets
  - jupyterlab
  - jupyterlab_code_formatter
  - leidenalg
  - line_profiler
  - matplotlib
  - minimap2
  - nd2reader
  - networkx
  - nodejs
  - numpy
  - openpyxl
  - pandas
  - pip
  - pip:
      - pulp
      - parse
      - h5py-cache
      - recombinator
  - pre-commit
  - pyarrow
  - pytables
  - python=3.11
  - pytorch
  - r-clustree
  - r-essentials
  - r-seurat
  - scanpy
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - tifffile
  - torchvision
  - tslearn
  - umap-learn
  - zarr
