name: agarpad
channels:
  - pytorch
  - nvidia
  - conda-forge
  - pyviz
  - bioconda
  - defaults
dependencies:
  - black
  - bokeh
  - dask
  - dask-jobqueue
  - dask-ml
  - datashader
  - distributed
  - fastparquet
  - h5py
  - holoviews
  - hvplot
  - ipywidgets
  - jupyterlab
  - jupyterlab_code_formatter
  - line_profiler
  - matplotlib
  - nd2reader
  - nodejs
  - numpy
  - pandas
  - pip
  - pip:
      - omnipose
      - pulp
      - parse
  - pre-commit
  - pyarrow
  - pytables
  - python=3.10.12
  - pytorch
  - pytorch-cuda=11.7
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - tifffile
  - torchaudio
  - torchvision
  - xarray
  - zarr
