## use flexible solve: mamba env create -f environment.yml --channel-priority flexible

name: agarpad
channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  # ---- python ----
  - python>=3.10,<3.12
  - pip

  # ---- formatting / dev ----
  - black
  - pre-commit

  # ---- jupyter / ux ----

  - jupyterlab
  - ipywidgets
  - jupyterlab_code_formatter

  # ---- core scientific stack ----
  - arch-py
  # - edt
  # - igraph
  # - python-igraph
  # - mahotas
  - nd2reader
  - numpy>2
  - scipy
  - pandas
  - scikit-image
  - scikit-learn
  - statsmodels
  # - segment-anything
  # - texttable
  - tifffile
  - h5py
  # - imagecodecs
  # - opencv
  - pytables
  - pyarrow
  # - roifile
  - xarray
  - zarr

  # ---- plotting / viz ----
  - matplotlib
  - seaborn
  - bokeh
  - datashader
  - hvplot
  - holoviews
  # - pbr
  - pyviz_comms

  # ---- dask / parallel ----
  - dask
  - distributed
  - dask-ml
  - dask-jobqueue
  - fastparquet

  # ---- pytorch + cuda (omnipo se-compatible) ----
  # - pytorch
  # - torchvision
  # - torchaudio
  # - pytorch-cuda=12.4
  - pytorch=2.5.*
  - torchvision=0.20.*
  - torchaudio=2.5.*
  - pytorch-cuda=12.4
  # - cudatoolkit=11.8

  # ---- pip-only deps ----
  - pip:
      - omnipose==1.0.6
      - cellpose==2.3.2
      - fastremap
      # - mgen
      - natsort
      - nd2
      # - ncolor
      - pulp
      - parse
      - "peakdetect @ git+https://github.com/erdogant/peakdetect.git@67d03304dfea5a33cd22f4e0990bee058bcdea0a" # contains scipy fix

      # - peakdetect
      # - torchvf
